<?php
/**
 * This file was generated by Nigatedev maker
 */
 
namespace App\Controller;

/**
 * undocumented class
 *
 * @package default
 * @subpackage default
 * @author `g:snips_author`
 */
class ControllerModel {
  
  public function index()
  {
    return "Hello ControllerModel";
  }
}
